name: flutter_marketplace
description: A Flutter NFT Marketplace on Polygon 
publish_to: 'none' 
version: 1.0.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  get_it: ^7.2.0
  http: ^0.13.4
  provider: ^6.0.2
  web3dart: ^2.3.5
  web_socket_channel: ^2.1.0

dev_dependencies:
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
